### PR TITLE
feat: integrate ai assistant

### PR DESCRIPTION
**Pull request by jaggerzhong**

### CODE REVIEW

**Comment by 9-2-1** [comment]
使用任意AI后端可能给Gandi带来风险。能够说下这个扩展后台用了什么AI服务？
---
Using an arbitary AI endpoint may be risky for Gandi. Could you tell me what AI service is behind the scene?

**Comment by fath11** [comment]
uhh
image
*image is in Cocrea

**Comment by jaggerzhong** [comment]
> uhh, its slightly not aligned image *image is in Cocrea
It's so weird, i've tried to reproduce the issue locally, but I haven't been able to. I'll investigate this further later today. Thanks for reaching out.

**Comment by kukemc** [comment]
哇趣 太酷了

**Pull request merged**
